import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import groupsRouter from "./groups";
import membersRouter from "./members";
import incidentTypesRouter from "./incident-types";
import reportsRouter from "./reports";
import pushRouter from "./push";
import billingRouter from "./billing";
import adminRouter from "./admin";
import invitationsRouter from "./invitations";
import escalationRouter from "./escalation";
import analyticsRouter from "./analytics";
import boundariesRouter from "./boundaries";
import widgetRouter from "./widget";
import apiKeysRouter from "./api-keys";
import v1Router from "./v1";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(groupsRouter);
router.use(membersRouter);
router.use(incidentTypesRouter);
router.use(reportsRouter);
router.use(pushRouter);
router.use(billingRouter);
router.use(adminRouter);
router.use(invitationsRouter);
router.use(escalationRouter);
router.use(analyticsRouter);
router.use(boundariesRouter);
router.use(widgetRouter);
router.use(apiKeysRouter);
router.use(v1Router);

export default router;
